# Generated by Django 4.2.14 on 2024-07-14 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0016_alter_attendanceclass_options_usersession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
